import './globals.css'
import {Inter} from 'next/font/google'
import {ReactNode} from 'react'
import {GlobalContext} from './globalContext'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <GlobalContext>
      {children}
    </GlobalContext>
    </body>
    </html>
  )
}
