name: "Continuous Deployment"
on:
  push:
    branches:
      - main
jobs:
  publish-prod-image:
    name: Push Prod Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: snippet-searcher-austral
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/snippet-searcher-austral/app-prod:latest
          build-args: |
            auth0_secret=${{ secrets.AUTH0_SECRET }}
            auth0_base_url=${{ secrets.AUTH0_BASE_URL_PROD }}
            auth0_issuer_base_url=${{ secrets.AUTH0_ISSUER_BASE_URL }}
            auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }}
            auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}
            auth0_audience=${{ secrets.AUTH0_AUDIENCE }}  

  deploy:
    needs: publish-prod-image
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 400 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PROD_SSH_PRIVATE}}
          SSH_KNOWN_HOSTS: ${{secrets.PROD_SSH_KNOWN_HOSTS}}

      - name: Connect via SSH and deploy
        run: |
          ssh -i $SSH_KEY_PATH mati@${{secrets.PROD_SSH_HOST}} "sudo bash -s" <<EOF
            bash deploy-script.sh "${{ secrets.GHCR_TOKEN }}" "app"
          EOF
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key